# Generated by Django 4.0.4 on 2022-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='salary',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
