# Generated by Django 4.0.4 on 2022-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giventask',
            name='category',
            field=models.CharField(choices=[('Onspot', 'Onspot'), ('Remotework', 'Remotework')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reached Completion', 'Reached Completion'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
